### ISSUE TITLE
Response is truncated somethimes

### ISSUE THREAD

**Issue by olvlvl** [digitarald/digitarald-fancyupload#11]
Hello,

For some mysterious reasons the JSON response is truncated sometimes :

"{"rc":{"element":"<div class=\"file-upload-element\"><var class=\"options\" style=\"display: none; font-size: .8em; font-family: monospace\">{\"path\":\"\\/$wd\\/wdpublisher\\/protected\\/modules\\/resources.files\\/public\\/fancyupload\\/Swiff.Uploader.swf\",\"fileSizeMax\":134217728}<\/var><div class=\"input\"><label>URL du fichier <small>(temporaire)<\/small>&nbsp;: <input name=\"path\" value=\"\/repository\/$temp\/phpJnbS1X.jpg\" readonly=\"readonly\" type=\"text\" \/><\/label> <button type=\"button\">Choisir un fichier<\/button>\n<small class=\"file-size-limit\" style=\"display: block; margin-top: .5em\">La taille du fichier doit \u00eatre inf\u00e9rieure \u00e0 128 Mo. <\/small><\/div><div class=\"infos\"><ul class=\"details\"><li><span title=\"Path: \/repository\/$temp\/phpJnbS1X.jpg\">phpJnbS1X.jpg<\/span><\/li><li>Image size: 1417&times;941px<\/li><li>Display ratio: 3%<\/li><li>981.66 Kb<\/li><\/ul><div class=\"preview\"><a href=\"\/repository\/$temp\/phpJnbS1X.jpg&amp;uniqid=4b20d50a77935\"

And it's completely random. Sometime it works, sometimes it doesn't. I was wandering if there is a limit to the Flash response buffer, or if anyone has experienced this, because it happens a lot where I work and I can't figure out the reason.

PS: It works perfectly on Windows, the problem seams to be with the flash player on OSX.

**Comment by digitarald** [comment]
do you try to send HTML encoded in JSON?
