### ISSUE TITLE
Upload dont work with Firefox/3.5b4

### ISSUE THREAD

**Issue by trollkarlen** [digitarald/digitarald-fancyupload#6]
I have a upload on my test page that works with safari but not with Firefox/3.5b4.
/T

**Comment by digitarald** [comment]
Mine works just fine, would you share your test page?

**Comment by trollkarlen** [comment]
I have it in a web2py test environment, and its on an internal server so it can be hard but i can send you the app so you can test it your self.

The error i get is:
Upload failed: Error caused a send or load operation to fail (Error #2038):

/T
