### ISSUE TITLE
Too much logic hidden in actionscript

### ISSUE THREAD

**Issue by ulope** [digitarald/digitarald-fancyupload#7]
In this release much of the actual functionality that used to live in FancyUpload2 has been moved into the actionscript source. This makes it unnecessarily difficult to adapt FancyUpload.

My specific use case: 
I have to remember uploaded files across page reloads. Now since there is no "manual" addFile method I can not "inject" the files into flash so they are only known on the JS side. This leads to problems if a user tries to delete such a file since flash doesn't know about them and consequently can't fire the "remove" event on the file. 

I solved this problem with a custom FileClass but still it's harder then it could be.

**Comment by digitarald** [comment]
How could you remember files over time, you? Validation happens event-based on JS side, so it is easy to add this and extending the File class is expected way.

I am however open to suggestions, what could be moved?
