### ISSUE TITLE
onFileStart for first file gets called too late

### ISSUE THREAD

**Issue by lukaswoj** [digitarald/digitarald-fancyupload#8]
Hi

I believe I found a bug.

To be quick I uploaded foto queue demo to my server.
http://www.ngs.kei.pl/fancyupload/build.html

The only thing I added is:

onFileStart: function( file )
{
  console.warn( 'onFileStart for ' + file.id );
}

Please take a look at firebug console and You will see when onFileStart is called for file 1

To be completely sure that You know what I saw I captured screenshot of my firebug console.
http://www.ngs.kei.pl/fancyupload.png

Thanks in advance and thanks for FancyUpload - its great stuff.
## 

Best regards
Lukasz Wojciechowski

**Comment by digitarald** [comment]
There is a 1ms delay for the firing event which solved Flash communication problems (calls need to be async to avoid race conditions that cause Flash to close the browser) should not result in problems. All events should still be in the correct order in JS, or do you have any problems with the delay?

**Comment by lukaswoj** [comment]
Im not sure if this comes form delay You described.
Please look at this screenshot: http://www.ngs.kei.pl/fancyupload.png
You will notice that onFileStart event handler is called too late for first file - look for string "onFileStart for 1". For the rest of files it is ok.

Can You see what I mean ?
