### ISSUE TITLE
Demo on the site does not work in Safari 4.0.3

### ISSUE THREAD

**Issue by joshuajonah** [digitarald/digitarald-fancyupload#9]
I am unable to determine if it is a problem with the fancyuploader or wether it's something with your comments. 

Safari error console log:

<pre>
[The HTML that caused this error was generated by a script.] Unmatched </link> encountered.  Ignoring tag.
show_ads.jsResource interpreted as script but transferred with MIME type text/html.
Unsafe JavaScript attempt to access frame with URL http://digitarald.de/project/fancyupload/3-0/showcase/photoqueue/ from frame with URL http://disqus.com/embed/reply.html?1254948964422&f=digitarald-de&t=fancyupload_swiff_meets_ajax_1_0&to_redirect=http%3A%2F%2Fdigitarald.de%2Fproject%2Ffancyupload%2F3-0%2Fshowcase%2Fphotoqueue%2F&ifrs=&def_email=&def_name=. Domains, protocols and ports must match.
</pre>

**Comment by digitarald** [comment]
Sorry, disqus will be killed soon, but a guy with a hammer and a wrench.
